// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using ProtonPack.Data;
using SqlSugar;
using System.Configuration;
using WebThree.Shared.Data;
using static WebThree.Shared.Utilities;

namespace ProtonPack.Data
{
    public class GroupDataManager : BaseDataManager<Group>
    {

        internal GroupDataManager(CompanyUser cu) : base(cu)
        {
        }

        public override Group Update(Group entity, Group item = null)
        {
            if( entity != null )
            {
                if (entity.ID == Guid.Empty)
                {
                    if(entity.Active == true)
                        return base.Update(entity, item);
                    else
                        throw new WebThreeException("Unable to disable the default group.");
                }
                else
                    return base.Update(entity, item);
            }
            else
                throw new WebThreeException("Group cannot be null.");
        }

        public override void Delete(Guid id)
        {
            if (id != Guid.Empty)
                base.Delete(id);
            else
                throw new WebThreeException("Unable to delete the default group.");
        }

        public override ISugarQueryable<Group> DefaultQuery()
        {
            var rc = base.DefaultQuery()
                .Mapper(r => r.Rules, r => r.Rules.First().GroupID)
                .Mapper(r => r.Customers, r => r.Customers.First().GroupID)
                // This doesn't currently work...thoughts?  (how to get child items for child items...)
                //.Mapper(r => r.Rules.First().RuleType, r => r.Rules.First().RuleTypeID)
                //.Mapper(r => r.Rules.First().BehaviorType, r => r.Rules.First().BehaviorTypeID)
                ;

            return rc;
        }
    }
}
#pragma warning restore 1591
