// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using ProtonPack.Data;
using System.Configuration;
using WebThree.Shared.Data;
using static WebThree.Shared.Utilities;

namespace ProtonPack.Data
{
    public class RuleParameterDataManager : BaseDataManager<RuleParameter>
    {

        internal RuleParameterDataManager(CompanyUser cu) : base(cu)
        {
        }

        public List<RuleParameter> GetParametersByRuleID(Guid ruleId)
        {
            return DefaultQuery(r => !r.Deleted && r.RuleID == ruleId).ToList();
        }
    }
}
#pragma warning restore 1591
