// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Linq;
using System.Text;
using SqlSugar;
using WebThree.Shared.Data;

namespace Zuul.Data
{
	[SugarTable("ContractSettings")]
    public partial class ContractSetting : IDataObject 
    {
		public ContractSetting()
		{
			ID = new Guid();
		}

        [SugarColumn(IsPrimaryKey=true, ColumnName="ContractSettingID")]
		public Guid ID { get; set; } 
        public string ContractAddress { get; set; }
        public int ContractType { get; set; }
        public string ContractDescription { get; set; }
        public int ChainID { get; set; }
        public string ChainURL { get; set; }
        public string PartnerContractID { get; set; }
        public int ContractMinterType { get; set; }
        public string ChainAPIKey { get; set; }
        public string Abi { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool Deleted { get; set; }
    }

}
#pragma warning restore 1591
