

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Zuul-T4`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=tcp:venkman-dev.database.windows.net,1433;Database=Zuul-DEV;User ID=gozer;password=**zapped**;`
//     Schema:                 `dbo`
//     Include Views:          `True`

//     Factory Name:          `SqlClientFactory`
// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using Zuul.Data;
using System.Configuration;
using WebThree.Shared.Data;

namespace Zuul.Data
{
	public static partial class DataManagerFactory
	{
		internal enum DataObjects
		{
			Company,
			ContractSetting,
			User,
			UserSession,
			Validation,
		}
	}
}
#pragma warning restore 1591
