// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Linq;
using System.Text;
using SqlSugar;
using WebThree.Shared.Data;

namespace ProtonPack.Data
{
	[SugarTable("Assets")]
    public partial class Asset : IDataObject 
    {
		public Asset()
		{
			ID = new Guid();
		}

        [SugarColumn(IsPrimaryKey=true, ColumnName="AssetID")]
		public Guid ID { get; set; } 
        public string AssetNumber { get; set; }
        public Guid? AssetOwnerID { get; set; }
        public string AssetData { get; set; }
        public Guid? AssetTypeID { get; set; }
        public Guid? ParentAssetID { get; set; }
        public string? Status { get; set; }
        public bool Deleted { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }

}
#pragma warning restore 1591
