// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using ProtonPack.Data;
using static WebThree.Shared.Utilities;

namespace ProtonPack.BusinessLogic
{
    public class CompanyManager : BaseBusinessLogicManager<Company>
    {
        public CompanyManager(CompanyUser companyUser) : base(companyUser) { }

        public Task<CompanySummary> GetSummary()
        {
            return Task.Run(() =>
            {
                using var manager = DataManagerFactory.GetDataManager<Company, CompanyDataManager>(companyUser);
                return manager.GetSummary(companyUser.CompanyId);
            });
        }

        public Task<Company> UpdateEnvironment( EnvironmentData envData )
        {
            return Task.Run(() =>
            {
                using var manager = DataManagerFactory.GetDataManager<Company, CompanyDataManager>(companyUser);
                return manager.UpdateEnvironment(envData);
            });
        }


    }
}
#pragma warning restore 1591
