// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using ProtonPack.Data;
using static WebThree.Shared.Utilities;

namespace ProtonPack.BusinessLogic
{
    public class CustomerManager : BaseBusinessLogicManager<Customer>
    {
        public CustomerManager(CompanyUser companyUser) : base(companyUser) { }



        public Customer GetByWalletAddress(string walletAddress)
        {
            return (manager as CustomerDataManager)?.GetByWalletAddress(walletAddress) ?? null as Customer;
        }

        public Task<CustomerSummary> GetSummary( Guid customerId )
        {
            return Task.Run(() =>
            {
                using var ruleManager = DataManagerFactory.GetDataManager<Customer, CustomerDataManager>(companyUser);
                return ruleManager.GetSummary(customerId);
            });
        }
    }
}
#pragma warning restore 1591
