// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using ProtonPack.Data;
using ProtonPack.BusinessLogic;
using static WebThree.Shared.Utilities;

namespace ProtonPack.BusinessLogic
{
    public class IpfsItemManager : BaseBusinessLogicManager<IpfsItem>
    {
        public IpfsItemManager(CompanyUser companyUser) : base(companyUser) { }

        public Task<List<IpfsItem>> GetByContractType()
        {
            return Task.Run(() =>
            {
                using var manager = DataManagerFactory.GetDataManager<IpfsItem, IpfsItemDataManager>(companyUser);
                return manager.GetByContractType(companyUser.ContractTypeId);
            });
        }
    }
}
#pragma warning restore 1591
